# -*- coding: utf-8 -*-
"""utils/session

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15PkxA3OPrrPj8IDU9sgoZ18hKW1So1fm
"""

# utils/session.py

import streamlit as st

def get_safe_dict(key: str) -> dict:
    """
    Récupère une clé du session_state en garantissant un dict.
    Corrige automatiquement list / None / autres types.
    """
    value = st.session_state.get(key, {})
    if not isinstance(value, dict):
        value = {}
        st.session_state[key] = value
    return value