# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WN6hjAHiBuoSW6joc97mmsSp0JXZB5RW
"""

# -*- coding: utf-8 -*-
"""
Module database
Gestion de la base de données SQLite pour l'application financière
"""